### PR TITLE
Merge remote-tracking branch 'upstream/master' into dash

### PR DESCRIPTION
**Pull request by oleksandrivantsiv**
**What I did**
- Merge remote-tracking branch 'upstream/master' into dash
- Fix compilation issue caused by missing include. After the merge from the master branch dashorch compilation stated to fail with "handleSaiRemoveStatus was not declared in this scope". The error is caused by the missing include of "saihelper.h" header file:
```
dash/dashvnetorch.cpp:130:45: error: 'handleSaiRemoveStatus' was not declared in this scope
  130 |         task_process_status handle_status = handleSaiRemoveStatus((sai_api_t) SAI_API_DASH_VNET, status);
      |                                             ^~~~~~~~~~~~~~~~~~~~~
```
**Why I did it**
Update the dash branch with the latest changes from the master branch.
**How I verified it**
- Run bgp_facts test
- Run dash vnet-to-vnet test

**Details if related**

### CODE REVIEW

**Comment by prsunny** [comment]
@oleksandrivantsiv , can you fix the build failure?

**Comment by oleksandrivantsiv** [comment]
@prsunny it depends on changes in sonic-sairedis repo. To solve the issue we need to update SAI and sonic-sairedis first

**Comment by liat-grozovik** [comment]
@prsunny @oleksandrivantsiv  should we merge it regardless?

**Comment by oleksandrivantsiv** [comment]
@prsunny all checkers passed, can you please merge this PR?

**Review by prsunny — APPROVED** [review]
