### PR TITLE
BFD hardware offload for BGP sessions

### PR DESCRIPTION
**Pull request by baorliu**
Original PR 3267 was messed up when trying to fix DCO error. this one is the replacement for that PR for code change reference. 

For detailed description and commit history, please refer the original PR:
https://github.com/sonic-net/sonic-swss/pull/3267

**What I did**
Provide an option to use hardware offloaded BFD to replace software BFD (frr/bfdd) for BGP neighbor reachability detection.

**Why I did it**
Hardware offloaded BFD usually provide more bfd sessions support, and has shorter detection time comparing to software bfd. and also lower CPU load because that BFD sessions are offloaded to hardware/ASIC.

**How I verified it**
* unit test
* The design was built into a sonic image, and verified in a hardware testbed. This design has been in multiple production image for more than one year.

**Details if related**
This program is built under sonic-swss, but running in bgp container.

HLD in PR review:
https://github.com/sonic-net/SONiC/pull/1599

[notes] some commit history are lost after a force push after fixing a DCO error.
git log before the force push:
```
commit 42c0b3ef874d3f58c10e03b29cdce29876cb497a
Author: Baorong Liu <96146196+baorliu@users.noreply.github.com>
Date:   Mon Feb 23 11:51:51 2026 -0800

    fix makefile
    
    Signed-off-by: Baorong Liu <96146196+baorliu@users.noreply.github.com>
commit 84d4c1bac48e93e3c6fcf80ddda75d4325e61484
Author: Baorong Liu <96146196+baorliu@users.noreply.github.com>
Date:   Tue Apr 29 13:07:18 2025 -0700

    add ut for bfdsyncd
    
    Signed-off-by: Baorong Liu <96146196+baorliu@users.noreply.github.com>
commit 32db91f472501b67f42b74dc16f3a5ece9c49c23
Author: Baorong Liu <96146196+baorliu@users.noreply.github.com>
Date:   Wed Feb 12 12:03:23 2025 -0800

    handle bgp restart case
    
    Signed-off-by: Baorong Liu <96146196+baorliu@users.noreply.github.com>

commit d9d71e8da3c2b3e7ae14557a01d3abed1d0eaa06
Author: Baorong Liu <96146196+baorliu@users.noreply.github.com>
Date:   Mon Nov 4 15:16:34 2024 -0800

    remove some debugging code
    
    Signed-off-by: Baorong Liu <96146196+baorliu@users.noreply.github.com>

commit 4e608ca1d163454dd0d70d1fa50e5d1a53839ad6
Author: Baorong Liu <baorliu@cisco.com>
Date:   Mon Aug 26 21:14:19 2024 -0700

    bgp bfd hardware offload initial commit
    
    Signed-off-by: Baorong Liu <96146196+baorliu@users.noreply.github.com>

### CODE REVIEW

File: bfdsyncd/bfdlink.cpp [hunk 1]
```diff
@@ -0,0 +1,722 @@
...
+    netfile.open(path);
+    std::getline(netfile, mac);
+    netfile.close();
+    return mac;
+}
+
+std::string BfdLink::exec(const char* cmd) {
+    std::array<char, 128> buffer;
+    std::string result;
+    std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(cmd, "r"), pclose);
```
Comment (vaishnav-nexthop) [inline bfdsyncd/bfdlink.cpp:128]: This line breaks the swss `.deb` build on Debian Trixie / GCC 14.2 with `-Werror=ignored-attributes`:
```
bfdsyncd/bfdlink.cpp:128:44: error: ignoring attributes on template argument 'int (*)(FILE*)' [-Werror=ignored-attributes]
```
`pclose` is declared in glibc with `__attribute__((nonnull))`, and that attribute is stripped when `decltype(&pclose)` is used as the Deleter template parameter to `std::unique_ptr`. GCC 13 (Bookworm) was silent about it, anyone moving to a Trixie-based slave image (`sonic-slave-trixie`) hits a hard build failure since swss builds `-Werror`.

File: bfdsyncd/bfdlink.cpp [hunk 2]
```diff
@@ -0,0 +1,722 @@
...
+            }
+            else if (value == "Down")
+            {
+                state = STATE_DOWN;
+            }
+        }
+        /* Remote discriminator. */
+        if (field == "remote_discriminator")
+        {
+            uint32_t rid = (uint32_t)strtoll(string(value).c_str(), NULL, 10);
```
Comment (vaishnav-nexthop) [inline bfdsyncd/bfdlink.cpp:683]: All four `strtoll(value.c_str(), NULL, 10)` calls in `handleBfdStateUpdate` silently return `0` on garbage input. A malformed `remote_discriminator` / `remote_min_rx` / `remote_min_tx` / `remote_multiplier` field in STATE_DB will be turned into a zero, packed into `msg.data.state.*`, and sent over the BFDDP socket to `bfdd` — the operator gets no signal that the state notification is corrupt.

Worth replacing with `swss::to_uint<uint32_t>(value)` inside a `try/catch (std::exception&)` so a bad row logs the offending field name and the function returns `false` before sending a partial frame.

File: bfdsyncd/bfdlink.cpp [hunk 3]
```diff
@@ -0,0 +1,722 @@
...
+            if (it->second.data.session.detect_mult != bmp->data.session.detect_mult)
+            {
+                changed = true;
+            };
+            if (changed) {
+                SWSS_LOG_WARN("bfd session key %s is already created, parameter changed, delete and recreate it.", bfdkey_map.c_str());
+                m_bfdTable.del(bfdkey);
+                m_key2bfd.erase(bfdkey_map);
+                /* the symptom observed that redis eliminates consecutive del and add transaction sometime, get wrong result. need to wait to make sure deletion done */
+                usleep(100000);
```
Comment (vaishnav-nexthop) [inline bfdsyncd/bfdlink.cpp:458]: Do the timer fields actually need a delete/recreate? Per `saibfd.h`, `MIN_TX`, `MIN_RX`, and `MULTIPLIER` are `CREATE_AND_SET`, so they should be modifiable in place via `set_bfd_session_attribute`. A delete/recreate bounces the session to Down momentarily — which can flap the BGP sessions BFD is protecting, defeating the point.

For the fields that *are* `CREATE_ONLY` (`MULTIHOP`, `CBIT`, `SRC_IP_ADDRESS`, `DST_IP_ADDRESS`, `LOCAL_DISCRIMINATOR`), delete/recreate is unavoidable

Comment (liu14187) [reply bfdsyncd/bfdlink.cpp:458]: The reason to use delete/recreate approach is to make it compatible with existing systems/vendors:
1, current orchagent/bfdorch does not support attribute update:
```
In create_bfd_session:
    if (bfd_session_map.find(key) != bfd_session_map.end())
    {
        SWSS_LOG_ERROR("BFD session for %s already exists", key.c_str());
        return true;
    }
```
2, with the delete/recreate approach, parameter update from frr/bfdd still works even some vendor does not support BFD attribute update in SAI. so it is safe for all the vendors who already support BFD HW offload, even that vendor does not support BFD (HW offload) attribute update.

Comment from Baorong Liu

**Comment by prsunny** [comment]
@baorliu , please address copilot comments and resolve conflict.

**Comment by prsunny** [comment]
Closing in favor of #4676
