### PR TITLE
[CONTAINER_TRIXIE][SWSS] Upgrade swss container to trixie

### PR DESCRIPTION
**Pull request by tirupatihemanth**
**What I did**
Make `sonic-swss` build cleanly inside the Debian Trixie–based SWSS container (GCC 14.2 / glibc 2.40 / newer libstdc++) so the orchagent image can be migrated off of Bookworm. Without these changes the swss build fails inside the Trixie container with `-Werror`-promoted warnings and missing-symbol errors.

**1. Suppress new GCC 14.x diagnostics that break `-Werror` (`configure.ac`)**
GCC 14.2 promotes/introduces a couple of warnings that fire on long-standing patterns in this tree. Both are intentional in our code or come from generated code, so they're added to `CFLAGS_COMMON` as `-Wno-`:

- `-Wno-overloaded-virtual` — GCC 14 is much stricter about flagging virtual-function hiding (a derived class declaring a method with the same name but a different signature than a base-class virtual). Several SWSS Orch / executor classes intentionally overload such names.
- `-Wno-calloc-transposed-args` — newly added in GCC 14; flags `calloc(size, count)` callsites where the arguments look transposed. Triggered by code we don't own (third-party / generated headers) and harmless functionally.

**2. Add explicit standard-library includes that are no longer pulled in transitively (Trixie/libstdc++ 14)**
Newer libstdc++ and glibc headers shipped in Trixie no longer transitively include some of the headers older releases happened to drag in, which broke the build:

- `lib/subintf.h` — add `#include <cstdint>`. `<string>` no longer transitively pulls in `<cstdint>` on libstdc++ 14, so `uint*_t` types used in this header become undefined.
- `fpmsyncd/routesync.h` — add `#include <unistd.h>`. POSIX symbols (e.g. `read`/`write`/`close`/`pipe`/related fd helpers) used by routesync are no longer transitively visible via `<bits/stdc++.h>` / `<linux/*>` on Trixie.

> **Note:** This PR must merge **before** the sonic-buildimage companion that flips `docker-orchagent` to the Trixie SWSS layer base, otherwise that build will fail on the same warnings/missing-symbol errors fixed here.

**Related PRs (must merge in this order):**
1. **This PR (sonic-swss)** — must merge first.
2. **sonic-buildimage companion**: [sonic-net/sonic-buildimage#27121](https://github.com/sonic-net/sonic-buildimage/pull/27121) — `[SWSS] Upgrade swss container to Trixie` (also bumps in-container Scapy 2.4.5 → 2.6.1.dev0 to fix warm-reboot on Python 3.13).

Tracking issue: [sonic-net/SONiC#2169](https://github.com/sonic-net/SONiC/issues/2169) — Container upgrades to Trixie.

**How I verified it**
- `sonic-swss` (and orchagent) build cleanly inside the Trixie SWSS layer container with `-Werror` enabled — no `overloaded-virtual` / `calloc-transposed-args` failures, no `uint32_t` / POSIX-symbol "not declared in this scope" failures.
- End-to-end build of the orchagent docker via the companion buildimage PR succeeds and the resulting `swss` container starts cleanly on a switch.
- Bookworm-based build is unaffected (the new `-Wno-*` flags are accepted by the older GCC and the new includes are no-ops on Bookworm libstdc++).

**Details if related**
- Companion sonic-buildimage PR: [sonic-net/sonic-buildimage#27121](https://github.com/sonic-net/sonic-buildimage/pull/27121).
- Tracking issue: [sonic-net/SONiC#2169](https://github.com/sonic-net/SONiC/issues/2169).

### CODE REVIEW

File: fpmsyncd/routesync.h [hunk 1]
```diff
@@ -11,6 +11,7 @@
 #include "warmRestartHelper.h"
 #include <string.h>
 #include <bits/stdc++.h>
+#include <unistd.h>
```
[the remark this answers is not in the document]
Comment (tirupatihemanth) [reply fpmsyncd/routesync.h:14]: Debian 13 comes with gcc/g++ 14.2 and many standard c system headers which used to come with c++ standard headers are not present anymore. We need to explicitly include unistd.h and cstdint them to be able to use data types like uint16_t otherwise we would get compilation errors in Trixie.

File: lib/subintf.h [hunk 2]
```diff
@@ -1,6 +1,7 @@
 #pragma once
 
 #include <string>
+#include <cstdint>
```
[the remark this answers is not in the document]
Comment (tirupatihemanth) [reply lib/subintf.h:4]: Debian 13 comes with gcc/g++ 14.2 and many standard c system headers which used to come with c++ standard headers are not present anymore. We need to explicitly include unistd.h and cstdint them to be able to use data types like uint16_t otherwise we would get compilation errors in Trixie.

File: configure.ac [hunk 3]
```diff
@@ -93,6 +93,8 @@ CFLAGS_COMMON+=" -Wno-aggregate-return"
 CFLAGS_COMMON+=" -Wno-padded"
 CFLAGS_COMMON+=" -Wno-switch-enum"
 CFLAGS_COMMON+=" -Wno-unused-parameter"
+CFLAGS_COMMON+=" -Wno-overloaded-virtual"
+CFLAGS_COMMON+=" -Wno-calloc-transposed-args"
```
[the remark this answers is not in the document]
Comment (tirupatihemanth) [reply configure.ac:97]: This assumption by copilot is wrong "If the build is done with a compiler that doesn't recognize one of these options (different GCC versions/Clang)"

In debian 13 we always build with gnu gcc 14.2 and it has gotten more strict with reporting specific warnings as error which was not there in previous gcc versions in bookworm.
Hence this is necessary and works reliably

**Review by dgsudharsan — APPROVED** [review]
